### ISSUE TITLE
Проблем при последната версия на Counter-Strike

### ISSUE THREAD

**Issue by martindchv** [OciXCrom/CromChat#1]
Относно бъга с чат съобщенията при последната версия на играта, за да се поправи просто трябва да се изтрие 161 ред от библиотеката. 

write_string("%s")

Тъй като много хора ми писаха за проблема реших да пиша тук, за да се поправи библиотеката.

**Comment by OciXCrom** [comment]
Обаче ако се махне този ред, ще може да се бъгва чата с #кодовете.

**Comment by martindchv** [comment]
По-добре отколкото изобщо да не работи. За fix на # има много начини, но за поправка на това - не.
